### ISSUE TITLE
Using unregistered C function `psmirnov2x` in `ps.summary.new`

### ISSUE THREAD

**Issue by jbiggsets** [mattcefalu/twang#14]
Hi @mattcefalu,

You may be working on updating this is the `fast` branch, but the C function `psmirnov2x` is being called using `.C()` here:

https://github.com/mattcefalu/twang/blob/fast/R/ps.summary.new.R#L122

However, this function does not appear to be registered in `init.c`:

https://github.com/mattcefalu/twang/blob/fast/src/init.c#L9-L11

(Also, I thought if you wanted to use `.C()`, it had to be with a subroutine that returns `void`, but maybe I'm wrong about that?)

**Comment by mattcefalu** [comment]
We use `.Call()` in [bal.stat.fast.R](https://github.com/mattcefalu/twang/blob/cfdc5f8f416b79fbeaf12f900c11317757c30294/R/bal.stat.fast.R). See here:

https://github.com/mattcefalu/twang/blob/cfdc5f8f416b79fbeaf12f900c11317757c30294/R/bal.stat.fast.R#L86

We will make a similar change here.

**Comment by jbiggsets** [comment]
Awesome.
